### PR TITLE
fix: show non-admin user his own permissions only

### LINKED ISSUE #241: /SASjsApi/permission -> should show OWN perms only else ALL if admin
API description should also be updated

### PR DESCRIPTION
**Pull request by sabhas**
## Issue

closes #241 

## Intent

* if user is admin, return all permission in response of  `SASjsApi/permission` else return user's permissions only
* update permission modal schema such that it should have path attribute instead of uri and add an additional attribute for permission type

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] Reviewer is assigned.

### CODE REVIEW

File: api/src/controllers/permission.ts [hunk 1]
```diff
@@ -71,7 +73,7 @@ export interface PermissionDetailsResponse {
 @Tags('Permission')
 export class PermissionController {
   /**
-   * @summary Get list of all permissions (uri, setting and userDetail).
+   * @summary Get a list of user's permissions, if user is admin all permissions are returned.
```
Comment (allanbowe) [inline api/src/controllers/permission.ts:76]: Do we have a 'details' section?

Summary: Get the list of permitted routes

Details:  Get the list of permitted routes available to the authenticated user.  If the user is an admin, all routes are returned.  In future, this endpoint will also include the permitted files & folders.

File: api/src/routes/api/spec/permission.spec.ts [hunk 2]
```diff
@@ -497,11 +495,11 @@ describe('permission', () => {
         .send()
         .expect(200)
 
-      expect(res.body).toHaveLength(3)
+      expect(res.body).toHaveLength(1)
```
Comment (YuryShkoda) [inline api/src/routes/api/spec/permission.spec.ts:498]: it would be nice to have some logic behind `1`

**Review by YuryShkoda — APPROVED** [review]

**Review by YuryShkoda — APPROVED** [review]

**Review by allanbowe — APPROVED** [review]
